// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#ifndef __BINDINGS_MY_GAME_H
#define __BINDINGS_MY_GAME_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct my_game_string_t {
  uint8_t*ptr;
  size_t len;
} my_game_string_t;

typedef struct example_my_game_my_plugin_api_coord_t {
  uint32_t   x;
  uint32_t   y;
} example_my_game_my_plugin_api_coord_t;

typedef struct example_my_game_my_plugin_api_monster_t {
  my_game_string_t   name;
  uint32_t   hp;
  example_my_game_my_plugin_api_coord_t   pos;
} example_my_game_my_plugin_api_monster_t;

typedef struct {
  example_my_game_my_plugin_api_monster_t *ptr;
  size_t len;
} example_my_game_my_plugin_api_list_monster_t;

typedef struct exports_example_my_game_my_expectations_coord_t {
  uint32_t   x;
  uint32_t   y;
} exports_example_my_game_my_expectations_coord_t;

typedef struct exports_example_my_game_my_expectations_monster_t {
  my_game_string_t   name;
  uint32_t   hp;
  exports_example_my_game_my_expectations_coord_t   pos;
} exports_example_my_game_my_expectations_monster_t;

// Imported Functions from `example:my-game/my-plugin-api`
extern void example_my_game_my_plugin_api_get_position(example_my_game_my_plugin_api_coord_t *ret);
extern void example_my_game_my_plugin_api_set_position(example_my_game_my_plugin_api_coord_t *pos);
extern void example_my_game_my_plugin_api_monsters(example_my_game_my_plugin_api_list_monster_t *ret);

// Exported Functions from `my-game`
void exports_my_game_run(void);

// Exported Functions from `example:my-game/my-expectations`
void exports_example_my_game_my_expectations_get_monster(exports_example_my_game_my_expectations_monster_t *ret);

// Helper Functions

void example_my_game_my_plugin_api_monster_free(example_my_game_my_plugin_api_monster_t *ptr);

void example_my_game_my_plugin_api_list_monster_free(example_my_game_my_plugin_api_list_monster_t *ptr);

void exports_example_my_game_my_expectations_monster_free(exports_example_my_game_my_expectations_monster_t *ptr);

// Transfers ownership of `s` into the string `ret`
void my_game_string_set(my_game_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void my_game_string_dup(my_game_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void my_game_string_free(my_game_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
