// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#include "my_game.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `example:my-game/my-plugin-api`

__attribute__((__import_module__("example:my-game/my-plugin-api"), __import_name__("get-position")))
extern void __wasm_import_example_my_game_my_plugin_api_get_position(uint8_t *);

__attribute__((__import_module__("example:my-game/my-plugin-api"), __import_name__("set-position")))
extern void __wasm_import_example_my_game_my_plugin_api_set_position(int32_t, int32_t);

__attribute__((__import_module__("example:my-game/my-plugin-api"), __import_name__("monsters")))
extern void __wasm_import_example_my_game_my_plugin_api_monsters(uint8_t *);

// Exported Functions from `my-game`


// Exported Functions from `example:my-game/my-expectations`

__attribute__((__weak__, __export_name__("cabi_post_example:my-game/my-expectations#get-monster")))
void __wasm_export_exports_example_my_game_my_expectations_get_monster_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + 4))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void example_my_game_my_plugin_api_monster_free(example_my_game_my_plugin_api_monster_t *ptr) {
  my_game_string_free(&ptr->name);
}

void example_my_game_my_plugin_api_list_monster_free(example_my_game_my_plugin_api_list_monster_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    example_my_game_my_plugin_api_monster_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      example_my_game_my_plugin_api_monster_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_example_my_game_my_expectations_monster_free(exports_example_my_game_my_expectations_monster_t *ptr) {
  my_game_string_free(&ptr->name);
}

void my_game_string_set(my_game_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void my_game_string_dup(my_game_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void my_game_string_free(my_game_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[20];

void example_my_game_my_plugin_api_get_position(example_my_game_my_plugin_api_coord_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_example_my_game_my_plugin_api_get_position(ptr);
  *ret = (example_my_game_my_plugin_api_coord_t) {
    (uint32_t) (uint32_t) (*((int32_t*) (ptr + 0))),
    (uint32_t) (uint32_t) (*((int32_t*) (ptr + 4))),
  };
}

void example_my_game_my_plugin_api_set_position(example_my_game_my_plugin_api_coord_t *pos) {
  __wasm_import_example_my_game_my_plugin_api_set_position((int32_t) ((*pos).x), (int32_t) ((*pos).y));
}

void example_my_game_my_plugin_api_monsters(example_my_game_my_plugin_api_list_monster_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_example_my_game_my_plugin_api_monsters(ptr);
  *ret = (example_my_game_my_plugin_api_list_monster_t) { (example_my_game_my_plugin_api_monster_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) };
}

__attribute__((__export_name__("run")))
void __wasm_export_exports_my_game_run(void) {
  exports_my_game_run();
}

__attribute__((__export_name__("example:my-game/my-expectations#get-monster")))
uint8_t * __wasm_export_exports_example_my_game_my_expectations_get_monster(void) {
  exports_example_my_game_my_expectations_monster_t ret;
  exports_example_my_game_my_expectations_get_monster(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + 4)) = ((ret).name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).name).ptr;
  *((int32_t*)(ptr + 8)) = (int32_t) ((ret).hp);
  *((int32_t*)(ptr + 12)) = (int32_t) (((ret).pos).x);
  *((int32_t*)(ptr + 16)) = (int32_t) (((ret).pos).y);
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_my_game(void);
void __component_type_object_force_link_my_game_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_my_game();
}
