vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO bytecodealliance/wasm-micro-runtime
    REF "WAMR-${VERSION}"
    SHA512 9a1dc0dd17dbf9111cf66a2d6a49565d52a005e5a024a20291cb274d826077aac46ff050c63b71503083301dfb32179a0fd3bfe2eddffce0cfb81a42a60fa439
    HEAD_REF main
)

set(WASMEDGE_CMAKE_OPTIONS "")

# list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_AOT_RUNTIME=OFF")

# if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_STATIC_LIB=OFF")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_SHARED_LIB=ON")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_LLVM_STATIC=OFF")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_TOOLS_STATIC=OFF")
# else()
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_STATIC_LIB=ON")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_SHARED_LIB=OFF")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_LLVM_STATIC=ON")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_TOOLS_STATIC=ON")
# endif()

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    aot WAMR_BUILD_AOT
    classic-interpreter WAMR_BUILD_INTERP
    fast-interpreter WAMR_BUILD_FAST_INTERP
    llvm-jit WAMR_BUILD_JIT
    fast-jit WAMR_BUILD_FAST_JIT
)
string(REPLACE "=ON" "=1" FEATURE_OPTIONS "${FEATURE_OPTIONS}")

message("FEATURE_OPTIONS:  ${FEATURE_OPTIONS}")

if (WAMR_BUILD_FAST_INTERP)
    set(WAMR_BUILD_INTERP ON)
endif ()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
    # OPTIONS_RELEASE
    #     -DCMAKE_INSTALL_BINDIR=${CURRENT_PACKAGES_DIR}/tools
    # OPTIONS_DEBUG
    #     -DCMAKE_INSTALL_BINDIR=${CURRENT_PACKAGES_DIR}/debug/tools
)

vcpkg_cmake_install()

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
