vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO bytecodealliance/wasm-micro-runtime
    REF "WAMR-${VERSION}"
    SHA512 9a1dc0dd17dbf9111cf66a2d6a49565d52a005e5a024a20291cb274d826077aac46ff050c63b71503083301dfb32179a0fd3bfe2eddffce0cfb81a42a60fa439
    HEAD_REF main
)

set(WASMEDGE_CMAKE_OPTIONS "")

# list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_AOT_RUNTIME=OFF")

# if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_STATIC_LIB=OFF")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_SHARED_LIB=ON")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_LLVM_STATIC=OFF")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_TOOLS_STATIC=OFF")
# else()
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_STATIC_LIB=ON")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_SHARED_LIB=OFF")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_LLVM_STATIC=ON")
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_LINK_TOOLS_STATIC=ON")
# endif()

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    aot WAMR_BUILD_AOT
    classic-interpreter WAMR_BUILD_INTERP
    fast-interpreter WAMR_BUILD_FAST_INTERP
    llvm-jit WAMR_BUILD_JIT
    fast-jit WAMR_BUILD_FAST_JIT
)

if (WAMR_BUILD_FAST_INTERP)
    set(WAMR_BUILD_INTERP ON)
endif ()

# # disabled due to build failure
# list(APPEND WASMEDGE_CMAKE_OPTIONS "-DWASMEDGE_BUILD_EXAMPLE=OFF")

# set(WASMEDGE_PLUGIN_WASI_NN_BACKEND "")

# if("plugin-wasi-nn-backend-openvino" IN_LIST FEATURES)
#     list(APPEND WASMEDGE_PLUGIN_WASI_NN_BACKEND "OpenVINO")
# endif()
# if("plugin-wasi-nn-backend-pytorch" IN_LIST FEATURES)
#     list(APPEND WASMEDGE_PLUGIN_WASI_NN_BACKEND "PyTorch")
# endif()
# if("plugin-wasi-nn-backend-tensorflow-lite" IN_LIST FEATURES)
#     list(APPEND WASMEDGE_PLUGIN_WASI_NN_BACKEND "TensorflowLite")
# endif()

# if(NOT WASMEDGE_PLUGIN_WASI_NN_BACKEND STREQUAL "")
#     list(JOIN WASMEDGE_PLUGIN_WASI_NN_BACKEND "," WASMEDGE_PLUGIN_WASI_NN_BACKEND)
#     list(APPEND WASMEDGE_CMAKE_OPTIONS "-WASMEDGE_PLUGIN_WASI_NN_BACKEND=${WASMEDGE_PLUGIN_WASI_NN_BACKEND}")
# endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${WASMEDGE_CMAKE_OPTIONS}
        # ${FEATURE_OPTIONS}
    # OPTIONS_RELEASE
    #     -DCMAKE_INSTALL_BINDIR=${CURRENT_PACKAGES_DIR}/tools
    # OPTIONS_DEBUG
    #     -DCMAKE_INSTALL_BINDIR=${CURRENT_PACKAGES_DIR}/debug/tools
)

vcpkg_cmake_install()

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
