vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO bytecodealliance/wasm-micro-runtime
    REF "WAMR-${VERSION}"
    SHA512 6f8b145172e8e79c8a20255e4875de5e4778c79f0ddf22d7e2e4258390d0770e180a8fdc75383bfb12310a2035bc8286ae76b474a8c2071a7be885c1d56c4b8c
    HEAD_REF main
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    aot WAMR_BUILD_AOT
    classic-interpreter WAMR_BUILD_INTERP
    fast-interpreter WAMR_BUILD_FAST_INTERP
    llvm-jit WAMR_BUILD_JIT
    fast-jit WAMR_BUILD_FAST_JIT
)
string(REPLACE "=ON" "=1" FEATURE_OPTIONS "${FEATURE_OPTIONS}")

message("FEATURE_OPTIONS:  ${FEATURE_OPTIONS}")

if (VCPKG_TARGET_IS_WINDOWS)
    message(STATUS "Disabling WAMR JIT features on Windows targets")
    set(FEATURE_OPTIONS)
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_PLATFORM=windows")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_TARGET=X86_64")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_INTERP=1")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_AOT=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_JIT=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_LIBC_BUILTIN=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_LIBC_WASI=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_FAST_INTERP=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_MULTI_MODULE=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_LIB_PTHREAD=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_MINI_LOADER=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_SIMD=0")
    list(APPEND FEATURE_OPTIONS "-DWAMR_BUILD_DEBUG_INTERP=0")
endif ()
message("FEATURE_OPTIONS:  ${FEATURE_OPTIONS}")

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
    # OPTIONS_RELEASE
    #     -DCMAKE_INSTALL_BINDIR=${CURRENT_PACKAGES_DIR}/tools
    # OPTIONS_DEBUG
    #     -DCMAKE_INSTALL_BINDIR=${CURRENT_PACKAGES_DIR}/debug/tools
)

vcpkg_cmake_install()

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
