name: MacOS

on:
  push:
    branches:
      - trunk
      - main
  pull_request:
    branches:
      - trunk
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "macos-13"
          - os: "macos-14"
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up C++20 
        uses: aminya/setup-cpp@v1
        with: 
          compiler: gcc-13
          cmake: true 
          ninja: true 
      
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: "build/vcpkg_installed/**/*"
          key: ${{ matrix.os }}-vcpkg_installed

      - name: install dependencies
        run: |
          brew install pkg-config autoconf autoconf-archive automake coreutils libtool cmake ninja

      - name: configure
        run: |
          cmake --preset linux-ninja-Debug

      - name: build
        run: |
          cmake --build --preset linux-ninja-Debug

      - name: test
        working-directory: build
        run: |
          ctest -VV
