name: Ubuntu

on:
  push:
    branches:
      - trunk
      - main
  pull_request:
    branches:
      - trunk
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "ubuntu-24.04"
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Cargo registry
        if: always() 
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('./Cargo.lock') }}
          path: ~/.cargo/registry
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache vcpkg registry
        if: always() 
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('./vcpkg*.json') }}
          path: build/vcpkg_installed/**/*
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: install dependencies
        run: |
          sudo apt-get install -y \
          autoconf \
          autoconf-archive \
          automake \
          build-essential \
          ninja-build

      - name: Install rust dependencies
        run: |
          cargo install wasm-tools wit-bindgen-cli 

      - name: configure
        run: |
          cmake --preset linux-ninja-Debug

      - name: build
        run: |
          cmake --build --preset linux-ninja-Debug

      - name: test
        working-directory: build
        run: |
          ctest -VV

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload error logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-logs
          path: ./**/*.log
