name: Ubuntu

on:
  push:
    branches:
      - trunk
      - main
  pull_request:
    branches:
      - trunk
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "ubuntu-22.04"
          - os: "ubuntu-24.04"
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: "build/vcpkg_installed/**/*"
          key: ${{ matrix.os }}-vcpkg_installed

      - name: install dependencies
        run: |
          sudo apt-get install -y \
          autoconf \
          autoconf-archive \
          automake \
          build-essential \
          ninja-build

      - name: configure
        run: |
          cmake --preset linux-ninja-Debug

      - name: build
        run: |
          cmake --build --preset linux-ninja-Debug

      - name: test
        working-directory: build
        run: |
          ctest -VV

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
