name: Windows

on:
  push:
    branches:
      - trunk
      - main
  pull_request:
    branches:
      - trunk
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "windows-2022"
            config: vcpkg-VS-17
            build: VS-17-Debug
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Cargo registry
        if: always() 
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('./Cargo.lock') }}
          path: ~/.cargo/registry
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache vcpkg registry
        if: always() 
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('./vcpkg*.json') }}
          path: build/vcpkg_installed/**/*
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install rust dependencies
        run: |
          cargo install wasm-tools wit-bindgen-cli 

      - name: configure
        run: |
          cmake --preset ${{ matrix.config }}

      - name: build
        run: |
          cmake --build --preset ${{ matrix.build }}

      - name: test
        working-directory: build
        run: |
          ctest -C Debug -VV 

      - name: Upload error logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-logs
          path: ./**/*.log
