name: Windows

on:
  push:
    branches:
      - trunk
      - main
  pull_request:
    branches:
      - trunk
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "windows-2022"
            config: vcpkg-VS-17
            build: VS-17-Debug
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: "build/vcpkg_installed/**/*"
          key: ${{ matrix.os }}-vcpkg_installed

      - name: configure
        run: |
          cmake --preset ${{ matrix.config }}

      - name: build
        run: |
          cmake --build --preset ${{ matrix.build }}

      - name: test
        working-directory: build
        run: |
          ctest -C Debug -VV
